# 3.8 연습문제

1번 MNIST 데이터셋으로 분류기를 만들어 테스트 세트에서 97% 정확도를 달성해보세요. **KNeighborsClassifier**가 이 작업에 아주 잘 맞습니다. 좋은 하이퍼파라미터 값만 찾으면 됩니다. (weights와 n_neighbors 하이퍼파라미터로 그리드 탐색을 시도해보세요.)

In [9]:
import warnings
warnings.filterwarnings('ignore')

In [6]:
from uidam_package import fetchData

X_train, y_train, X_test, y_test = fetchData.fetch_mnist()

In [ ]:
X_train = X_train.reshape((60000, 28*28))
X_test = X_test.reshape((10000, 28*28))

In [7]:
print(X_train.shape)
print(y_train.shape)

(60000, 28, 28)
(60000,)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from uidam_package import model

param_grid = {
    'n_neighbors' : [3, 5, 7],
    'weights' : ['uniform', 'distance']
}

model_name = "grid_search_knn_clf.pkl"

if model.model_exists(model_name):
    grid_search_knn_clf = model.get_model(model_name)
else:
    knn_clf = KNeighborsClassifier()
    grid_search_knn_clf = GridSearchCV(knn_clf, param_grid, cv=5, scoring='neg_mean_squared_error', return_train_score=True)
    grid_search_knn_clf.fit(X_train, y_train)
    model.save_model(grid_search_knn_clf, model_name)

In [ ]:
grid_search_knn_clf.cv_results_

In [ ]:
best_model = grid_search_knn_clf.best_estimators_

2번. MNIST 이미지를 어느 방향으로든 한 픽셀 이동시킬 수 있는 함수를 만들어보세요. 그런 다음 훈련세트에 있는 각 이미지에 대해 네 개의 이동된 복사본 (방향마다 한 개씩) 을 만들어 훈련 세트에 추가하세요. 마지막으로 이 확장된 데이터셋에서 앞에서 찾은 최선의 모델을 훈련시키고 테스트 세트에서 정확도를 측정해보세요. 모델 성능이 더 높아졌는지 확인하세요! 인위적으로 훈련 세트를 늘리는 이 기법을 **데이터 증식** 또는 **훈련 세트 확장 Training Set Expansion** 이라고 합니다.

3번. 타이타닉 데이터셋에 도전해보세요. (생략)

4번. 스팸 분류기를 만들어보세요. (아주 도전적인 과제입니다.)
- 아파치 스팸어쌔신 공공 데이터셋에서 스팸과 햄 샘플을 내려받습니다.
- 훈련 세트와 테스트 세트로 나눕니다.
- 각 이메일을 특성 벡터로 변환하는 데이터 준비 파이프라인을 만듭니다. 이 준비 파이프라인은 하나의 이메일을 가능한 단어의 존재 여부를 나타내는 (희소) 벡터로 바꿔야 합니다. 예를 들어, 모든 이메일이 네 개의 단어 'Hello', 'how', 'are', 'you'만 포함한다면 'Hello you Hello Hello you'라는 이메일은 벡터 [1, 0, 0, 1]로 변환되거나, 단어의 출현 횟수에 관심이 있다면 [3, 0, 0, 2]로 변환되어야 합니다.
- 준비 파이프라인에 이메일 헤더 제거, 소문자 변환, 구두점 제거, 모든 URLs 주소를 'URL'로 대체, 모든 숫자를 'NUMBER'로 대체, **어간** 추출 등을 수행할지 여부를 제어하기 위해 하이퍼파라미터를 추가합니다.
- 여러 분류기를 시도해보고 재현율과 정밀도가 모두 높은 스팸 분류기를 만들 수 있는지 확인해보세요.

In [28]:
import bz2
import os
import tarfile

target_path = os.path.join("datasets", "spam")

file_list = os.listdir(target_path)

for file_name in file_list:
    if('bz2' not in file_name): continue
    file_path = os.path.join(target_path, file_name)
    extracted_file_path = file_path[:-4]
    print(extracted_file_path)
    
    if os.path.exists(extracted_file_path): continue

    with open(file_path, 'rb') as f_in:
        with open(extracted_file_path, 'wb') as f_out:
            for data in iter(lambda : f_in.read(100 * 1024), b''):
                f_out.write(data)

file_list = os.listdir(target_path)

for file_name in file_list:
    if('bz2' in file_name): continue
    file_path = os.path.join(target_path, file_name)
    tar = tarfile.open(file_path)
    extracted_file_path = file_path[:-4]
    tar.extractall(extracted_file_path)
    tar.close()

datasets\spam\20021010_easy_ham.tar
datasets\spam\20021010_hard_ham.tar
datasets\spam\20021010_spam.tar
datasets\spam\20030228_easy_ham.tar
datasets\spam\20030228_easy_ham_2.tar
datasets\spam\20030228_hard_ham.tar
datasets\spam\20030228_spam.tar
datasets\spam\20030228_spam_2.tar
datasets\spam\20050311_spam_2.tar


In [68]:
X = np.array([])

np.append(X, [1, 2, 3])
np.append(X, [4, 5, 6])

array([4., 5., 6.])

In [125]:
list(map([1,2,3], str)

SyntaxError: unexpected EOF while parsing (<ipython-input-125-355eca1163cb>, line 1)

In [129]:
import numpy as np

X = np.array([])
y = np.array([])

target_path = os.path.join("datasets", "spam")
file_list = os.listdir(target_path)

for file_name in file_list:
    file_path = os.path.join(target_path, file_name)
    if(os.path.isdir(file_path)):
        inner_folder_name = os.listdir(file_path)[0]
        files_path = os.path.join(file_path, inner_folder_name)
        add_file = os.listdir(files_path)
        add_file = list(map(lambda x : os.path.join(files_path, x), add_file))
        if('spam' in inner_folder_name):
            X = np.append(X, add_file)
            y = np.append(y, [1] * len(add_file))
        elif('ham' in inner_folder_name):
            X = np.append(X, add_file)
            y = np.append(y, [0] * len(add_file))
        else:
            print("NOPE")

In [130]:
# Train, Test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2)

In [131]:
np.histogram(y_train, bins=2)[0]/len(y_train)

array([0.64686047, 0.35313953])

In [132]:
np.histogram(y_test, bins=2)[0]/len(y_test)

array([0.64667596, 0.35332404])

In [198]:
stri = "<HEAD> hello </HEAD>dd"

import re

a = re.compile('<HEAD>(.*)</HEAD>')
a.sub('', stri)

'dd'

In [465]:
from sklearn.base import BaseEstimator, TransformerMixin
import re
from collections import Counter

class wordSparseVector(BaseEstimator, TransformerMixin):
    def __init__(self, remove_header = True, is_lowercase = True):
        self.remove_header = remove_header
        self.is_lowercase = is_lowercase
        pass
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):
        email = np.random.choice(X)
        X_transformed = []
        with open(email, 'rb') as f_in:
            contents = f_in.read().decode('cp1252')

            if self.remove_header:
                remover = re.compile('<HEAD>.*</HEAD>')
                contents = remover.sub('', contents)

            if self.is_lowercase:
                contents = contents.lower()

            word_vec = contents.split()
            X_transformed.append(Counter(word_vec))
        return X_transformed
            
wordSparseVector().fit_transform(X_train)

[Counter({'from': 6,
          'rssfeeds@jmason.org': 1,
          'mon': 1,
          'oct': 5,
          '7': 3,
          '12:05:14': 1,
          '2002': 5,
          'return-path:': 1,
          '<rssfeeds@spamassassin.taint.org>': 2,
          'delivered-to:': 1,
          'yyyy@localhost.spamassassin.taint.org': 1,
          'received:': 3,
          'localhost': 2,
          '(jalapeno': 1,
          '[127.0.0.1])': 2,
          'by': 5,
          'jmason.org': 1,
          '(postfix)': 1,
          'with': 5,
          'esmtp': 2,
          'id': 2,
          '9693816f76': 1,
          'for': 5,
          '<jm@localhost>;': 1,
          'mon,': 4,
          '12:03:52': 2,
          '+0100': 3,
          '(ist)': 2,
          'jalapeno': 1,
          '[127.0.0.1]': 1,
          'imap': 1,
          '(fetchmail-5.9.0)': 1,
          'jm@localhost': 1,
          '(single-drop);': 1,
          '07': 2,
          'dogma.slashnull.org': 2,
          '(localhost': 1,
          '(8.11